language: cpp
dist: trusty
compiler:
  - gcc
  - clang
os:
  - linux

before_script:
  - sudo apt-get install libboost-all-dev libcurl4-openssl-dev
  - export CTEST_OUTPUT_ON_FAILURE=1

script: cmake . && make && make test